defaults:
  - _self_
  - config: unet

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}

config:
  dataset: 'dataset name'
  data_path: 'path/to/data'
  gt_path: 'path/to/gt'
  pred_data_path: 'path/to/pred_data'
  pred_gt_path: 'path/to/pred_gt'




  init_type: 'kaiming'  # ['normal', 'xavier', 'xavier_uniform', 'kaiming', 'orthogonal', 'none]
  aug: True  # True or False
  epochs: 100 # ? 100 
  epochs_per_checkpoint: 25
  batch_size: 4
  num_workers: 8
  samples_per_volume: 10
  init_lr: 0.01
  scheduler_step_size: 20
  scheduler_gamma: 0.8
  cudnn_enabled: True
  cudnn_benchmark: True
  use_scheduler: True
  sampler_type: 'label'  # ['uniform', 'label']
  suffix: '.nii.gz'
  debug_mode: False

  cycle_val: ${config.train.cycle_val}
  cycle_val_fold: ${config.train.cycle_val_fold}
  cycle_req_list: ${config.train.cycle_req_list}

  val_per_n_epochs: 5 # ? 5
  
  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}